name: build_on_push

on: [push]

env:
  BUILD_TYPE: Release

jobs:

  #---------------------------------------------------------------------
  # MTL target CI

  build_TGT:
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        target: [rp2040, rp2350]

    steps:
    - uses: actions/checkout@v6
      with:
       submodules: 'recursive'

    - name: Install dependencies
      run:  brew install arm-none-eabi-gcc

    - name: Prepare build
      run: mkdir -p ${{github.workspace}}/build/${{matrix.target}}

    - name: Configure build
      working-directory: ${{github.workspace}}/build/${{matrix.target}}
      shell: bash
      run: cmake ../.. -DCMAKE_TOOLCHAIN_FILE=PDK/TGT/${{matrix.target}}/toolchain.cmake

    - name: Build
      working-directory: ${{github.workspace}}/build/${{matrix.target}}
      shell: bash
      run: make

    - uses: actions/upload-artifact@v7
      with:
        name: pico-106_${{matrix.target}}
        path: |
          ${{github.workspace}}/build/${{matrix.target}}/*.uf2
